apiVersion: experiment.cbse.terministic.de/alpha2
kind: SimulationExperiment
metadata:
  labels:
    app.kubernetes.io/name: experiment-operator
    app.kubernetes.io/managed-by: kustomize
  name: simulationexperiment-loadbalancer
  namespace: default
spec:
  defaultServiceType: LoadBalancer
  detailDatabase:
    image: busybox:latest
    command: ["tail"]
    args: ["-f", "/dev/null"]
    dbname: simulation_db
    user: postgres
    password: postgres
    port: 5432
    serviceType: LoadBalancer
  resultDatabase:
    image: busybox:latest
    command: ["tail"]
    args: ["-f", "/dev/null"]
    dbname: result_db
    user: postgres
    password: postgres
    port: 5432
    serviceType: LoadBalancer
  translator:
    image: busybox:latest
    command: ["tail"]
    args: ["-f", "/dev/null"]
    repository: translator-repo
    baseimage: translator-baseimage
    serviceType: LoadBalancer
    port: 8080
  postProcessingService:
    image: busybox:latest
    command: ["tail"]
    args: ["-f", "/dev/null"]
    serviceType: LoadBalancer
    port: 8081
  experimentalDesignService:
    design: |
      This experiment runs multiple simulation scenarios
      to benchmark system behavior under varying load profiles
      and records performance metrics for analysis.
    image: busybox:latest
    command: ["tail"]
    args: ["-f", "/dev/null"]
    serviceType: LoadBalancer
    port: 8082
