apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-config
data:
  nats-server.conf: |
    port: 4222
    http_port: 8222

    jetstream {
      store_dir: "/data/jetstream"
      max_mem_store: 256MB
      max_file_store: 1GB
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
  labels:
    app: nats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
        - name: nats
          image: nats:2.11-alpine
          imagePullPolicy: IfNotPresent
          args:
            - "-c"
            - "/etc/nats-config/nats-server.conf"
          ports:
            - containerPort: 4222
              name: client
            - containerPort: 8222
              name: monitor
          volumeMounts:
            - name: nats-config
              mountPath: /etc/nats-config
            - name: jetstream-data
              mountPath: /data/jetstream
      volumes:
        - name: nats-config
          configMap:
            name: nats-config
        - name: jetstream-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nats
  labels:
    app: nats
spec:
  selector:
    app: nats
  ports:
    - name: client
      port: 4222
      targetPort: client
    - name: monitor
      port: 8222
      targetPort: monitor
