apiVersion: experiment.cbse.terministic.de/alpha2
kind: SimulationExperiment
metadata:
  name: sm-eds-e2e
  namespace: default
spec:
  defaultServiceType: ClusterIP
  detailDatabase:
    image: busybox:latest
    command: ["tail"]
    args: ["-f", "/dev/null"]
    dbname: simulation_db
    user: postgres
    password: postgres
    port: 5432
    serviceType: ClusterIP
  resultDatabase:
    image: busybox:latest
    command: ["tail"]
    args: ["-f", "/dev/null"]
    dbname: result_db
    user: postgres
    password: postgres
    port: 5432
    serviceType: ClusterIP
  translator:
    image: busybox:latest
    command: ["tail"]
    args: ["-f", "/dev/null"]
    repository: translator-repo
    baseimage: translator-baseimage
    serviceType: ClusterIP
    port: 8080
  postProcessingService:
    image: busybox:latest
    command: ["tail"]
    args: ["-f", "/dev/null"]
    serviceType: ClusterIP
    port: 8081
  experimentalDesignService:
    design: "SM EDS integration test"
    image: eds-mock:sm-e2e
    serviceType: ClusterIP
    port: 8082
